--[[
Claude colorscheme for Neovim (dark version)
--]]
local M = {}

local colors = {
  -- Base neutrals (dark)
  crust   = "#5e5d59",
  mantle  = "#3d3d3a",
  base    = "#141413", -- background

  -- Surface / overlay
  surface0 = "#87867f",
  surface1 = "#b0aea5",
  surface2 = "#d1cfc5",
  overlay0 = "#cbcadb",
  overlay1 = "#f0eee6",
  overlay2 = "#faf9f5",

  -- Text
  text   = "#e8e6dc",

  -- Accent colors from Claude brand
  blue     = "#6a9bcc",
  teal     = "#bcd1ca",
  green    = "#788c5d",
  yellow   = "#ebdbbc",
  orange   = "#d97757",
  orangeRed= "#c6613f",
  purple   = "#c46686",
  pink     = "#ebcece",
  grey     = "#cbcadb",
}

function M.setup()
  local highlights = {
    -- Editor basics
    Normal       = { fg = colors.text,   bg = colors.base },
    CursorLine   = { bg = colors.mantle },
    CursorLineNr = { fg = colors.text,   style = "bold" },
    Visual       = { bg = colors.surface0 },
    Search       = { bg = colors.blue,    fg = colors.base },
    IncSearch    = { bg = colors.orange,  fg = colors.base },
    LineNr       = { fg = colors.surface1 },
    SignColumn   = { bg = colors.base },
    VertSplit    = { fg = colors.surface0 },
    VertSplitNC  = { fg = colors.surface0 },
    StatusLine   = { fg = colors.text,   bg = colors.mantle, style = "bold" },
    StatusLineNC = { fg = colors.surface1, bg = colors.mantle },
    Title        = { fg = colors.orange, style = "bold" },
    Statement    = { fg = colors.orange },
    Conditional  = { fg = colors.orange },
    Repeat       = { fg = colors.orange },
    Label        = { fg = colors.orange },
    Operator     = { fg = colors.text },
    Keyword      = { fg = colors.orange },
    Exception    = { fg = colors.orange },
    PreProc      = { fg = colors.blue },
    Include      = { fg = colors.blue },
    Define       = { fg = colors.blue },
    Macro        = { fg = colors.blue },
    PreCondit    = { fg = colors.blue },
    Constant     = { fg = colors.orange },
    String       = { fg = colors.green },
    Character    = { fg = colors.green },
    Number       = { fg = colors.orange },
    Boolean      = { fg = colors.orange },
    Float        = { fg = colors.orange },
    Identifier   = { fg = colors.text },
    Function     = { fg = colors.pink },
    Underlined   = { fg = colors.blue, style = "underline" },
    Todo         = { bg = colors.yellow, fg = colors.base, style = "bold" },
    Comment      = { fg = colors.surface1, style = "italic" },
    Type         = { fg = colors.purple },
    StorageClass = { fg = colors.purple },
    Structure    = { fg = colors.purple },
    Typedef      = { fg = colors.purple },
    Special      = { fg = colors.orange },
    SpecialChar  = { fg = colors.orange },
    Tag          = { fg = colors.orange },
    Delimiter    = { fg = colors.surface2 },
    SpecialComment = { fg = colors.surface1, style = "italic" },
    Debug        = { fg = colors.orange },
    dir          = { fg = colors.text },
    link         = { fg = colors.blue, style = "underline" },
    -- Diagnostics
    DiagnosticError   = { fg = colors.orange },
    DiagnosticWarn    = { fg = colors.yellow },
    DiagnosticInfo    = { fg = colors.blue },
    DiagnosticHint    = { fg = colors.teal },
    DiagnosticOk      = { fg = colors.green },
    -- Treesitter
    ["@variable"]              = { fg = colors.text },
    ["@variable.builtin"]      = { fg = colors.orange },
    ["@parameter"]             = { fg = colors.text },
    ["@parameter.reference"]   = { fg = colors.text },
    ["@function"]              = { fg = colors.pink },
    ["@function.builtin"]      = { fg = colors.orange },
    ["@function.call"]         = { fg = colors.pink },
    ["@method"]                = { fg = colors.pink },
    ["@method.call"]           = { fg = colors.pink },
    ["@constructor"]           = { fg = colors.purple },
    ["@constant"]              = { fg = colors.orange },
    ["@constant.builtin"]      = { fg = colors.orange },
    ["@constant.macro"]        = { fg = colors.orange },
    ["@module"]                = { fg = colors.text },
    ["@module.builtin"]        = { fg = colors.orange },
    ["@label"]                 = { fg = colors.orange },
    ["@attribute"]             = { fg = colors.purple },
    ["@attribute.builtin"]     = { fg = colors.orange },
    ["@property"]              = { fg = colors.text },
    ["@punctuation.delimiter"] = { fg = colors.surface2 },
    ["@punctuation.bracket"]   = { fg = colors.surface2 },
    ["@punctuation.special"]   = { fg = colors.orange },
    ["@string"]                = { fg = colors.green },
    ["@string.regexp"]         = { fg = colors.orange },
    ["@string.escape"]         = { fg = colors.orange },
    ["@string.special"]        = { fg = colors.orange },
    ["@character"]             = { fg = colors.green },
    ["@character.special"]     = { fg = colors.orange },
    ["@boolean"]               = { fg = colors.orange },
    ["@number"]                = { fg = colors.orange },
    ["@float"]                 = { fg = colors.orange },
    ["@type"]                  = { fg = colors.purple },
    ["@type.builtin"]          = { fg = colors.purple },
    ["@variable.member"]       = { fg = colors.text },
    ["@variable.parameter"]    = { fg = colors.text },
    ["@function.call"]         = { fg = colors.pink },
    ["@constructor"]           = { fg = colors.purple },
    ["@conditional"]           = { fg = colors.orange },
    ["@repeat"]                = { fg = colors.orange },
    ["@label"]                 = { fg = colors.orange },
    ["@operator"]              = { fg = colors.text },
    ["@keyword"]               = { fg = colors.orange },
    ["@keyword.function"]      = { fg = colors.orange },
    ["@keyword.operator"]      = { fg = colors.orange },
    ["@keyword.return"]        = { fg = colors.orange },
    ["@conditional.ternary"]   = { fg = colors.orange },
    ["@punctuation"]           = { fg = colors.surface2 },
    ["@comment"]               = { fg = colors.surface1, style = "italic" },
    ["@comment.todo"]          = { bg = colors.yellow, fg = colors.base, style = "bold" },
    ["@comment.error"]         = { fg = colors.orange },
    ["@comment.warning"]       = { fg = colors.yellow },
    ["@comment.hint"]          = { fg = colors.teal },
    ["@comment.info"]          = { fg = colors.blue },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

return M
